AWSTemplateFormatVersion: "2010-09-09"

Description: This AWS CloudFormation Template creates the necessary resources that a security admin can leverage for appropriate role assignments to specific job functions that
             are needed for creating and maanging a certificate authority and issuing private certificates using ACM Private CA

# This IAM user will be used for all login and development
Resources:
   # We will use admin privileges for now and make it least privilege as we learn
   CaAdminRole:
      Type : AWS::IAM::Role
      Properties:
         RoleName: 'CaAdminRole'
         AssumeRolePolicyDocument:
           Version: "2012-10-17"
           Statement:
            -
               Effect: "Allow"
               Principal:
                  AWS: !Sub "${AWS::AccountId}"
               Action: 
                 - "sts:AssumeRole"
         Policies: 
            -
               PolicyName: "CaAdminRolePolicy"
               PolicyDocument: 
                  Version: "2012-10-17"
                  Statement: 
                      - 
                        Effect: "Allow"
                        Resource: "*"
                        Action: 
                           - acm-pca:ImportCertificateAuthorityCertificate
                           - acm-pca:TagCertificateAuthority
                           - acm-pca:ListTags
                           - acm-pca:GetCertificate
                           - acm-pca:UntagCertificateAuthority
                           - acm-pca:GetCertificateAuthorityCertificate
                           - acm-pca:RevokeCertificate
                           - acm-pca:UpdateCertificateAuthority
                           - acm-pca:ListCertificateAuthorities
                           - acm-pca:DescribeCertificateAuthorityAuditReport
                           - acm-pca:CreateCertificateAuthorityAuditReport
                           - acm-pca:RestoreCertificateAuthority
                           - acm-pca:IssueCertificate
                           - acm-pca:CreateCertificateAuthority
                           - acm-pca:GetCertificateAuthorityCsr
                           - acm-pca:DeletePermission
                           - acm-pca:DescribeCertificateAuthority
                           - acm-pca:CreatePermission
                           - acm-pca:ListPermissions
                           - acm-pca:DeleteCertificateAuthority
                           - acm:DescribeCertificate
                           - acm:ListCertificates
                           - acm:ListTagsForCertificate
                              
         ManagedPolicyArns: 
            - arn:aws:iam::aws:policy/AWSCertificateManagerPrivateCAPrivilegedUser
            - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
            - arn:aws:iam::aws:policy/AmazonS3FullAccess
            - arn:aws:iam::aws:policy/IAMReadOnlyAccess
            - arn:aws:iam::aws:policy/AmazonSNSReadOnlyAccess
            
    # We will use admin privileges for now and make it least privilege as we learn
   AppDevRole:
      Type : AWS::IAM::Role
      Properties:
         RoleName: 'AppDevRole'
         AssumeRolePolicyDocument:
           Version: "2012-10-17"
           Statement:
             -
               Effect: "Allow"
               Principal:
                  AWS: !Sub "${AWS::AccountId}"
               Action: 
                 - "sts:AssumeRole"
         Policies: 
         -
            PolicyName: "AppDevACMPolicy"
            PolicyDocument: 
               Version: "2012-10-17"
               Statement: 
                - 
                  Effect: "Allow"
                  Action: 
                    - acm:ListCertificates
                    - acm:ListTagsForCertificate
                    - acm:DescribeCertificate
                    - acm:RequestCertificate
                    - acm:DeleteCertificate
                    - acm-pca:IssueCertificate
                    - acm-pca:ListTags
                    - acm-pca:GetCertificate
                    - acm-pca:GetCertificateAuthorityCertificate
                    - acm-pca:RevokeCertificate
                    - acm-pca:ListCertificateAuthorities
                    - acm-pca:CreatePermission
                    - acm-pca:ListPermissions
                    - acm-pca:DescribeCertificateAuthority
                  Resource: "*"
         ManagedPolicyArns: 
            - arn:aws:iam::aws:policy/AWSCertificateManagerPrivateCAUser
            - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
            - arn:aws:iam::aws:policy/AWSLambdaFullAccess
            - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
            - arn:aws:iam::aws:policy/AmazonEC2FullAccess
            - arn:aws:iam::aws:policy/AmazonS3FullAccess
            - arn:aws:iam::aws:policy/AWSCloud9User
            - arn:aws:iam::aws:policy/IAMFullAccess
            - arn:aws:iam::aws:policy/AmazonSSMFullAccess
            
   
  
         
            



